# Basic SSL enabled taky setup for oneliner install
version: "3.7"
services:
#This is responsible for routing messages
   taky-cot:
    image: skadakar/taky:safepoint
    container_name: taky-cot
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      - mon_port=1337
      - mode=cot
      - bind_ip=$IP
      - public_ip=${IP}
      - hostname=stas.snekwerks.com
    volumes:
      - /root/taky-data/:/data
#This is responsible for routing data
   taky-data:
    depends_on:
      - taky-cot
    image: skadakar/taky:safepoint
    container_name: taky-data
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      - mon_port=1337
      - mode=data
      - bind_ip=$IP
      - public_ip=${IP}
      - hostname=stas.snekwerks.com
    volumes:
      - /root/taky-data/:/data
#RTSP - Video streaming server
   rtsp-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - RTSP_PROTOCOLS=tcp
#RTSP-ASN-SIDECAR - Contains a bot to do some helpful things
   node-red:
    container_name: taky-asn-sidecar
    user: "1000"
    network_mode: host
    restart: unless-stopped
    image: skadakar/taky-asn-sidecar:latest
    environment:
      - SERVER_ID=${ID}
