# Basic SSL enabled taky setup for oneliner install
version: "3.7"
services:
#This is responsible for routing messages
   taky-cot:
    image: skadakar/taky:debug
    container_name: taky-cot
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      #- client_cert_required=true
      - mode=cot
      #- bind_ip=$IP
      - public_ip=${IP}
      #- hostname=temp.airsoftnorge.com
    volumes:
      - /root/taky-data/:/data
      
#This is responsible for routing data
   taky-data:
    image: skadakar/taky:debug
    container_name: taky-data
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      #- client_cert_required=true
      - mode=data
      #- bind_ip=$IP
      - public_ip=${IP}
     # - hostname=temp.airsoftnorge.com
    volumes:
      - /root/taky-data/:/data
